# Generated by Django 3.2.18 on 2023-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20230726_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('userpw', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
