"""
Django settings for childcarrymap project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import db_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-3cj!a+t*htma7m7f6xc!u^xou-&)hx7d3)c-8#-uwyj&#p)_ob'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#호스트 주소(장고가 접속할 주소만 모두 입력)
ALLOWED_HOSTS = [
    # "FrontEnd-ALB-688336399.us-east-2.elb.amazonaws.com", #프론트 로드밸런서 주소
    "BackEndServer-ALB-1230290334.us-east-2.elb.amazonaws.com", #백엔드 로드밸런서 주소
    "10.0.133.7", # private-ec2-east-2a(private)
    "10.0.153.167", # private-ec2-east-2b(private)
    "127.0.0.1", #로컬호스트
    # "https://www.childcarrymap.click",
    "server.childcarrymap.click", #백엔드 로드밸런서 -> dns주소(https로 변경가능)
    "localhost"
]


# Application definition

INSTALLED_APPS = [
    "corsheaders",  # CORS 추가
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'map',
    'rest_framework',  # rest framework 추가 
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # CORS 추가
    "django.middleware.common.CommonMiddleware",  # CORS 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'childcarrymap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'childcarrymap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = db_settings.DATABASES
SECRET_KEY = db_settings.SECRET_KEY


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS 추가-로컬
CORS_ORIGIN_WHITELIST = ("http://127.0.0.1:8000", "http://localhost:3000")
CORS_ALLOW_CREDENTIALS = True

# CORS 클라우드
# CORS_ORIGIN_WHITELIST = ("http://127.0.0.1:8000", 
#                          "http://3.14.219.5", 
#                          "http://BackEndServer-ALB-1230290334.us-east-2.elb.amazonaws.com", 
#                          "http://FrontEnd-ALB-688336399.us-east-2.elb.amazonaws.com",
#                          "https://www.childcarrymap.click",
#                          "https://server.childcarrymap.click",
#                          "https://lb.childcarrymap.click"
#                          )

# CORS_ALLOW_CREDENTIALS = True
